language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

script: npm test

before_script:
  - npm install
  - psql -c "create database more-recipe-test" -U postgres
  - sequelize db:migrate

after_success: npm run coverage

services:
  - postgresql